- Frigate Face Bridge:
    href: http://homeassistant.localdomain:8123/b3b46a83_frigate_face_bridge
    description: HA Add-on-Webseite fuer Frigate Face Bridge
    icon: mdi-face-recognition
    ping: http://fossflow.localdomain:8099/health
